sudo: required

dist: trusty

addons:
  hosts:
    - iemdb
    - iemdb-hads
    - iemdb2
env:
  matrix:
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.6
language: python

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa -y
  - sudo apt-get update -qq

install:
  # Install miniconda
  # -----------------
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

  # Create the basic testing environment
  # ------------------------------------
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls yes
  - conda update -q conda
  - . $HOME/miniconda/etc/profile.d/conda.sh
  - conda create -n test-environment python=$PYTHON_VERSION
  - conda activate test-environment
  
  # Customise the testing environment
  # ---------------------------------
  - conda config --add channels conda-forge
  - conda install --file requirements.txt

script:
  - trial -r epoll pyldm/tests/test_ldmbridge.py;
