sudo: required

dist: bionic

addons:
  hosts:
    - iemdb
    - iemdb-hads
    - iemdb2
env:
  matrix:
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.6
    - PYTHON_VERSION=3.7
    - PYTHON_VERSION=3.8
language: python

install:
  - git clone --depth 1 https://github.com/akrherz/ci_tooling.git .ci_tooling
  - . .ci_tooling/miniconda.sh
  
  # Customise the testing environment
  # ---------------------------------
  - pip install --upgrade .

script:
  - trial -r epoll pyldm/tests/test_ldmbridge.py;
